

services:
  backend:
    container_name: inventory_system
    build:
      context: ./inventory-management  # Points to Django project folder
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - ./inventory-management:/usr/src/app
    depends_on:
      - redis
    env_file:
      - ./inventory-management/.env  # Correct path to .env file
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: ./inventory-management  # Uses the same build as backend
    container_name: celery_worker
    command: celery -A inventory worker --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - ./inventory-management/.env  # Correct path to .env file
    restart: always

  celery-beat:
    build: ./inventory-management  # Uses the same build as backend
    container_name: celery_beat
    command: celery -A inventory beat --loglevel=info
    depends_on:
      - backend
      - redis
      - celery
    env_file:
      - ./inventory-management/.env  # Correct path to .env file
    restart: always
