services:
  backend:
    container_name: inventory_system
    build:
      context: .  # ✅ Fix: This should be the current directory
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
      - .env  # ✅ Ensure .env is in the root folder
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .  # ✅ Uses the same build as backend
    container_name: celery_worker
    command: celery -A inventory worker --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - .env
    restart: always

  celery-beat:
    build: .  # ✅ Fix: Use the same build context
    container_name: celery_beat
    command: celery -A inventory beat --loglevel=info
    depends_on:
      - backend
      - redis
      - celery
    env_file:
      - .env
    restart: always
